#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "nextcloud-signaling"
name = "Nextcloud Signaling"
description.en = "Standalone signaling server in order to meet more than 3 persons onto Nextcloud Talk"
description.fr = "Serveur de signalisation autonome pour rencontrer plus de 3 personnes sur Nextcloud Talk"

version = "2.0.0~ynh2"

maintainers = ["ljf"]

[upstream]
license = "AGPL-3.0"
code = "https://github.com/strukturag/nextcloud-spreed-signaling"

[integration]
yunohost = ">= 12.0.4"
helpers_version = "2.1"
architectures = "all"
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/standalone-signaling"

    [install.backends_urls]
    ask.en = "Backend url"
    type = "string"
    example = "https://cloud.example.com"
    help = "Configure the first Nextcloud instance to allow the use this signaling server. After the installation, you will be able to add others instances from the app configuration panel."

    [install.turn_endpoints]
    ask.en = "TURN server endpoints"
    type = "string"
    example = "turn:domain.tld:3478?transport=udp,turn:domain.tld:3478?transport=tcp"
    help.en = "You need at least one Coturn or eturn servers. Coturn is packaged for YunoHost so you should probably install it first."

    [install.turn_api_key]
    ask.en = "TURN API key"
    type = "string"

    [install.turn_secret]
    ask.en = "TURN secret"
    type = "string"


[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/strukturag/nextcloud-spreed-signaling/releases/download/v2.0.3/nextcloud-spreed-signaling-v2.0.3.tar.gz"
    sha256 = "2b76556d3a551d2890756156d91878568f5fdbc0f6906a002621343466962200"

    # autoupdate.strategy = "latest_github_tag"

    [resources.system_user]
    home = "/var/www/__APP__"

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    main.allowed = "visitors"
    main.auth_header = false
    main.show_tile = false
    main.protected = true

    [resources.ports]
    main.default = 8080
    janus_http.default = 8188
    janus_ws.default = 8188
    nats.default = 4222

    [resources.apt]
    packages = "automake, build-essential, python3, protobuf-compiler, nats-server, janus"
