#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

hash_key=$(ynh_string_random --length=64)
block_key=$(ynh_string_random --length=32)
shared_secret=$(ynh_string_random --length=64)
ynh_app_setting_set --key=hash_key --value=$hash_key
ynh_app_setting_set --key=block_key --value=$block_key
ynh_app_setting_set --key=shared_secret --value=$shared_secret

# Backend password generation
while IFS= read -r backend_url
do
    backend_id=$(echo $backend_url | sed s@^https://@@ | sed 's/[.-]/_/g' | sed s@/@_@g)
    varname="pwd__${backend_id}"
    declare "$varname"=$(ynh_string_random)
    ynh_app_setting_set --key=$varname --value=${!varname}
done <<< "$backends_urls"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

chown -R "$app:$app" "$install_dir"

#=================================================
# BUILD
#=================================================
ynh_script_progression "Building go nextcloud signaling server..."

ynh_go_install
if [ ! -f /etc/profile.d/goenv.sh ]; then
    echo 'export PATH="/opt/goenv/bin:$PATH"' > /etc/profile.d/goenv.sh
    echo 'eval "$(goenv init -)"' >> /etc/profile.d/goenv.sh
fi
chmod u+x /etc/profile.d/goenv.sh
source /etc/profile.d/goenv.sh

GOCACHE=/opt/goenv/cache
export GOCACHE
pushd $install_dir
make build
popd
ynh_go_remove
chown -R "$app:$app" "$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

# Signaling server
mkdir -p /etc/$app/
ynh_config_add --jinja --template="server.conf" --destination="/etc/$app/server.conf"
chmod -R 400 "/etc/$app"
chmod u+x "/etc/$app"
chown -R "$app:$app" "/etc/$app"

# Janus
mkdir -p /etc/janus
ynh_config_add --template="janus.jcfg" --destination="/etc/janus/janus.jcfg"
ynh_config_add --template="janus.transport.http.jcfg" --destination="/etc/janus/janus.transport.http.jcfg"
ynh_config_add --template="janus.transport.websockets.jcfg" --destination="/etc/janus/janus.transport.websockets.jcfg"

chmod -R 400 "/etc/janus"

# Nats-server
ynh_config_add --template="nats-server.conf" --destination="/etc/nats-server.conf"
chmod -R 400 "/etc/nats-server.conf"
chown -R "nats:nats" "/etc/nats-server.conf"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "janus" --description="Janus server for nextcloud talk"
yunohost service add "nats-server" --description="Nats server for nextcloud talk"
yunohost service add "$app" --description="Signaling server for nextcloud talk" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="janus" --action="restart"
ynh_systemctl --service="nats-server" --action="restart"
ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
