#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

### $install_dir will automatically be initialized with some decent
### permissions by default... however, you may need to recursively reapply
### ownership to all files such as after the ynh_setup_source step
chown -R "$app:www-data" "$install_dir"

#=================================================
# RESTORE CONFIGURATIONS
#=================================================
# Signaling server
ynh_restore "/etc/$app"
chown -R "$app:$app" "/etc/$app"

# Janus
ynh_restore "/etc/janus/janus.jcfg"
ynh_restore "/etc/janus/janus.transport.http.jcfg"
ynh_restore "/etc/janus/janus.transport.websockets.jcfg"

# Nats-server
ynh_restore "/etc/nats-server.conf"
chown -R "nats:nats" "/etc/nats-server.conf"

#=================================================
# RESTORE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

### This should be a symetric version of what happens in the install script

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore "/etc/systemd/system/$app.service"
systemctl enable "$app.service" --quiet

yunohost service add "janus" --description="Janus server for nextcloud talk"
yunohost service add "nats-server" --description="Nats server for nextcloud talk"
yunohost service add "$app" --description=Signaling server for nextcloud talk --log=/var/log/$app/$app.log

ynh_restore "/etc/logrotate.d/$app"

#ynh_restore "/etc/fail2ban/jail.d/$app.conf"
#ynh_restore "/etc/fail2ban/filter.d/$app.conf"
#ynh_systemctl --action=restart --service=fail2ban

#=================================================
# RESTORE VARIOUS FILES
#=================================================

ynh_restore "/var/log/$app/"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

ynh_systemctl --service="janus" --action="restart"
ynh_systemctl --service="nats-server" --action="restart"
ynh_systemctl --service="$app" --action="start"

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
